### ISSUE TITLE
Code block is not working properly

### ISSUE THREAD

**Issue by lddfg** [Orc/discount#202]
I want to use the code block, but it doesn't work.
e.g.
### Input:
````
```
<h1>Hello world!</h1>
```
````

### output:
````
<p>```</p>

<h1>Hello world!</h1>


<p>```</p>
````

### But I think it should be output like this:
````
<pre><code>...</code></pre>
````

Of course, using -fnohtml can satisfy my needs, but I feel that sometimes I need to use html.

*Sorry, my english is poor, I hope you can understand what I mean.*

**Comment by Orc** [comment]
Use -ffencedcode to enable tilde and backtick code blocks

**Comment by lddfg** [comment]
I used it, but it doesn't work.
I use a backslash, but it parses something wrong. It caused my browser to execute the js code that should be displayed directly, which is very bad, I attacked myself.
Thank you very much, I hope you can understand what I mean.

**Comment by Orc** [comment]
How are you calling discount to compile your markdown source?  Are you doing it through the library interface or via the markdown program?

**Comment by godcrying** [comment]
I have the same problem. When there is an empty line in the code block, the block will be split into two `<p></p>`tags. For example:

input is:

````
there is a code block:
```rust
let user1 = User {
    username: String::from("someone"),

    email: String::from("someone@exp.com"),
    active: true,
    sign_in_count: 1,
}
```
````

and the output will be:

````
<p>there is a code block:
```rust
let user1 = User {
    username: String::from(&ldquo;someone&rdquo;),</p>

<pre><code>email: String::from("someone@exp.com"),
active: true,
sign_in_count: 1,
</code></pre>

<p>}
```</p>
````
it seems that there must be a blank line before code blocks, otherwise the output will be messed up as above.

**Comment by Orc** [comment]
Okay, I have pushed a fix for html inside code blocks (and space in code blocks as well), so it's ready for testing.

Yes, there needs to be a blank line before a code block;  paragraphs are grabby.

**Comment by lddfg** [comment]
Okay, I will test it later. Thank you very much for your work.

**Comment by lddfg** [comment]
This is a bad news.It still doesn't work, and this change has made the correct situation worse. 
This modification made the situation worse even if the code was not started with the html tag.
## Input
````
It's work?

```html
hhh
<h1>Hello world!</h1>
```
````
## Output
````
<p>It&rsquo;s work?</p>

<p>```html
hhh</p>

<h1>Hello world!</h1>


<p>```</p>
````

**Comment by Orc** [comment]
Did you pass the fencedcode option to discount?   There's a problem with the patch with -ffencedcode (it moves the prior paragraph down below the codeblock, which makes me think I was not tying off a list properly) but `markdown -ffencedcode` gives me

~~~~
<pre><code class="html">hhh
&lt;h1&gt;Hello world!&lt;/h1&gt;
</code></pre>
~~~~~

for the input of
~~~~
```html
hhh
<h1>Hello world!</h1>
```
~~~~

**Comment by lddfg** [comment]
Okay, it works very well. I am very sorry for the mistakes I made in the past when I was tired. It works very well now, thank you for your work.
*Note: As you might guess, the reason for this test error is because -ffencedcode is not used.*

**Comment by Orc** [comment]
Don't worry about missing the -ffencedcode flag in your test (one of the reasons I built the sanity test suite was that I kept forgetting flags when trying to manually do checks.)
